---
- hosts: dev
  become: true
  tasks:
   - name: Install latest version of Apache
     apt: name=apache2 update_cache=yes state=latest
   - raw: "echo Welcome to in28minutes | sudo tee /var/www/html/index.html"
  handlers:
   - name: restart-apache
     service:
       name: apache2
       state: restarted
